/** Заалтын жагсаалт / төлбөрийн grid-д шаардлагатай талбарууд (бүтэн document биш). */
export const METER_READING_LIST_SELECT = {
  id: true,
  meterId: true,
  organizationId: true,
  month: true,
  year: true,
  startValue: true,
  endValue: true,
  heatUsage: true,
  usage: true,
  baseClean: true,
  baseDirty: true,
  cleanPerM3: true,
  dirtyPerM3: true,
  cleanAmount: true,
  dirtyAmount: true,
  heatBase: true,
  heatPerM3: true,
  heatPerM2: true,
  heatAmount: true,
  subtotal: true,
  vat: true,
  total: true,
  paidAmount: true,
  heatClosed: true,
  paymentReference: true,
  smsSentAt: true,
  approved: true,
  ebarimtStatus: true,
  ebarimtBillId: true,
  ebarimtLastError: true,
  createdBy: true,
  createdAt: true,
  updatedAt: true,
} as const
